FROM openjdk:22-jdk
#COPY pom.xml /tmp/
#COPY src /tmp/src/
RUN mkdir -p /mtdrworkshop/creds
COPY wallet/ /mtdrworkshop/creds
WORKDIR /tmp/
EXPOSE 8080
COPY target/MyTodoList-0.0.1-SNAPSHOT.jar MyTodoList.jar

ENV ui_username="your_ui_username"
ENV ui_password="your_ui_password"

ENV db_user="your_db_user"
ENV dbpassword="your_db_password"
ENV db_url="jdbc:oracle:thin:@your_db_instance?TNS_ADMIN=/mtdrworkshop/creds"
ENV driver_class_name="oracle.jdbc.OracleDriver"

ENTRYPOINT [ "java", "-jar", "MyTodoList.jar" ]