package com.springboot.MyTodoList.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;

/*
 * ============================================================
 *  Entity: DocumentTT
 *  Table:  DOCUMENT_TT
 * ============================================================
 *
 *  Represents a project document uploaded by the team.
 *  Documents are stored in OCI Object Storage and go through a
 *  background embedding pipeline that converts them to vector
 *  embeddings for use with the AI chatbot (RAG pattern).
 *
 *  embed_status tracks where a document is in that pipeline:
 *    'loading' → file uploaded, embedding job queued/running
 *    'loaded'  → embeddings ready, document is searchable via AI
 *
 *  date_upload uses TIMESTAMP (not DATE) because upload time
 *  precision matters for ordering and deduplication.
 *
 *  Oracle DDL:
 *    CREATE TABLE document_tt (
 *        doc_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *        name_pj_doc     VARCHAR2(300),
 *        url_obj_store   VARCHAR2(300),
 *        date_upload     TIMESTAMP,
 *        embed_status    VARCHAR2(30) CHECK (embed_status IN ('loading', 'loaded')),
 *        pj_id           NUMBER REFERENCES project_tt(pj_id) ON DELETE CASCADE
 *    );
 */
@Entity
@Table(name = "DOCUMENT_TT")
public class DocumentTT {

    /*
     * Surrogate primary key — auto-generated by Oracle IDENTITY.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "DOC_ID")
    private long docId;

    /*
     * Display name of the document as it appears in the project UI.
     * e.g., "Sprint 1 Requirements.pdf"
     */
    @Column(name = "NAME_PJ_DOC", length = 300)
    private String namePjDoc;

    /*
     * Full URL or path within OCI Object Storage.
     * Used by the embedding service to download and process the file.
     * e.g., "https://objectstorage.us-phoenix-1.oraclecloud.com/.../doc.pdf"
     */
    @Column(name = "URL_OBJ_STORE", length = 300)
    private String urlObjStore;

    /*
     * Exact timestamp of upload — LocalDateTime maps to Oracle TIMESTAMP.
     * Precision matters here for ordering files within the same second.
     */
    @Column(name = "DATE_UPLOAD")
    private LocalDateTime dateUpload;

    /*
     * Current state in the embedding pipeline.
     * DocumentTTService monitors 'loading' documents for stuck jobs.
     * The AI query layer only searches documents with 'loaded' status.
     */
    @Column(name = "EMBED_STATUS", length = 30)
    private String embedStatus;

    /*
     * The project this document belongs to.
     * Cascading delete in Oracle means: delete project → delete its documents.
     */
    @Column(name = "PJ_ID")
    private long pjId;

    // ─── Constructors ────────────────────────────────────────────────────

    /** Required no-args constructor for JPA. */
    public DocumentTT() {}

    /** Full constructor for programmatic document creation. */
    public DocumentTT(long docId, String namePjDoc, String urlObjStore,
                      LocalDateTime dateUpload, String embedStatus, long pjId) {
        this.docId       = docId;
        this.namePjDoc   = namePjDoc;
        this.urlObjStore = urlObjStore;
        this.dateUpload  = dateUpload;
        this.embedStatus = embedStatus;
        this.pjId        = pjId;
    }

    // ─── Getters & Setters ───────────────────────────────────────────────

    public long getDocId()                         { return docId; }
    public void setDocId(long docId)               { this.docId = docId; }

    public String getNamePjDoc()                   { return namePjDoc; }
    public void setNamePjDoc(String namePjDoc)     { this.namePjDoc = namePjDoc; }

    public String getUrlObjStore()                 { return urlObjStore; }
    public void setUrlObjStore(String urlObjStore) { this.urlObjStore = urlObjStore; }

    public LocalDateTime getDateUpload()           { return dateUpload; }
    public void setDateUpload(LocalDateTime d)     { this.dateUpload = d; }

    public String getEmbedStatus()                 { return embedStatus; }
    public void setEmbedStatus(String embedStatus) { this.embedStatus = embedStatus; }

    public long getPjId()                          { return pjId; }
    public void setPjId(long pjId)                 { this.pjId = pjId; }
}
