package com.springboot.MyTodoList.model;

import jakarta.persistence.*;

/*
 * Entity: FeatureTT  →  FEATURE_TT table
 *
 * A Feature groups related tasks inside a sprint. It inherits the sprint's
 * date window (date_start_spr / date_end_spr are read from SPRINT_TT at
 * query time). Story points are computed dynamically as the sum of all
 * tasks that belong to this feature — no stored column.
 *
 * Oracle DDL (add to migration script):
 *   CREATE TABLE feature_tt (
 *       feature_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *       name_feature     VARCHAR2(300),
 *       priority_feature VARCHAR2(30),
 *       spr_id           NUMBER NOT NULL,
 *       CONSTRAINT chk_priority_feature
 *           CHECK (priority_feature IN ('high', 'medium', 'low')),
 *       CONSTRAINT fk_feature_sprint
 *           FOREIGN KEY (spr_id) REFERENCES sprint_tt(spr_id) ON DELETE CASCADE
 *   );
 *
 *   ALTER TABLE task_tt ADD feature_id NUMBER;
 *   ALTER TABLE task_tt ADD CONSTRAINT fk_task_feature
 *       FOREIGN KEY (feature_id) REFERENCES feature_tt(feature_id) ON DELETE SET NULL;
 */
@Entity
@Table(name = "FEATURE_TT")
public class FeatureTT {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "FEATURE_ID")
    private long featureId;

    @Column(name = "NAME_FEATURE", length = 300)
    private String nameFeature;

    @Column(name = "PRIORITY_FEATURE", length = 30)
    private String priorityFeature;

    @Column(name = "SPR_ID", nullable = false)
    private long sprId;

    public FeatureTT() {}

    public FeatureTT(long featureId, String nameFeature, String priorityFeature, long sprId) {
        this.featureId = featureId;
        this.nameFeature = nameFeature;
        this.priorityFeature = priorityFeature;
        this.sprId = sprId;
    }

    public long getFeatureId()                          { return featureId; }
    public void setFeatureId(long featureId)            { this.featureId = featureId; }

    public String getNameFeature()                      { return nameFeature; }
    public void setNameFeature(String nameFeature)      { this.nameFeature = nameFeature; }

    public String getPriorityFeature()                  { return priorityFeature; }
    public void setPriorityFeature(String p)            { this.priorityFeature = p; }

    public long getSprId()                              { return sprId; }
    public void setSprId(long sprId)                    { this.sprId = sprId; }
}
