package com.springboot.MyTodoList.model;

import jakarta.persistence.*;
import java.time.LocalDate;

/*
 * ============================================================
 *  Entity: ProjectTT
 *  Table:  PROJECT_TT
 * ============================================================
 *
 *  Represents a software project tracked in TaskTuner.
 *  A project acts as the top-level container for sprints, tasks,
 *  team members (via PROJECT_USER_TT), and documents.
 *
 *  The dual end-date design (set vs real) is intentional:
 *    - date_end_set_pj  = the originally planned deadline
 *    - date_end_real_pj = the actual close date (NULL while open)
 *  Comparing the two gives a simple schedule-adherence metric.
 *
 *  Oracle DDL:
 *    CREATE TABLE project_tt (
 *        pj_id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *        name_pj             VARCHAR2(300),
 *        date_start_pj       DATE,
 *        date_end_set_pj     DATE,
 *        date_end_real_pj    DATE
 *    );
 */
@Entity
@Table(name = "PROJECT_TT")
public class ProjectTT {

    /*
     * Surrogate primary key — auto-generated by Oracle IDENTITY.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "PJ_ID")
    private long pjId;

    /*
     * Human-readable project name (e.g., "Apollo Website Redesign").
     */
    @Column(name = "NAME_PJ", length = 300)
    private String namePj;

    /*
     * The date work on the project officially began.
     * LocalDate maps to Oracle DATE (date-only, no time component).
     */
    @Column(name = "DATE_START_PJ")
    private LocalDate dateStartPj;

    /*
     * The planned/committed deadline for the project.
     * Established at kickoff and rarely changed.
     */
    @Column(name = "DATE_END_SET_PJ")
    private LocalDate dateEndSetPj;

    /*
     * The actual date the project was closed.
     * Remains NULL while the project is still active.
     * Set by the manager when marking a project as complete.
     */
    @Column(name = "DATE_END_REAL_PJ")
    private LocalDate dateEndRealPj;

    // ─── Constructors ────────────────────────────────────────────────────

    /** Required no-args constructor for JPA proxy instantiation. */
    public ProjectTT() {}

    /** Full constructor for programmatic entity creation. */
    public ProjectTT(long pjId, String namePj, LocalDate dateStartPj,
                     LocalDate dateEndSetPj, LocalDate dateEndRealPj) {
        this.pjId           = pjId;
        this.namePj         = namePj;
        this.dateStartPj    = dateStartPj;
        this.dateEndSetPj   = dateEndSetPj;
        this.dateEndRealPj  = dateEndRealPj;
    }

    // ─── Getters & Setters ───────────────────────────────────────────────

    public long getPjId()                          { return pjId; }
    public void setPjId(long pjId)                 { this.pjId = pjId; }

    public String getNamePj()                      { return namePj; }
    public void setNamePj(String namePj)           { this.namePj = namePj; }

    public LocalDate getDateStartPj()              { return dateStartPj; }
    public void setDateStartPj(LocalDate d)        { this.dateStartPj = d; }

    public LocalDate getDateEndSetPj()             { return dateEndSetPj; }
    public void setDateEndSetPj(LocalDate d)       { this.dateEndSetPj = d; }

    public LocalDate getDateEndRealPj()            { return dateEndRealPj; }
    public void setDateEndRealPj(LocalDate d)      { this.dateEndRealPj = d; }
}
