package com.springboot.MyTodoList.model;

import jakarta.persistence.*;
import java.time.LocalDate;

/*
 * ============================================================
 *  Entity: SprintTT
 *  Table:  SPRINT_TT
 * ============================================================
 *
 *  Represents a time-boxed iteration (sprint) inside a project.
 *  Following Scrum, a sprint groups tasks together under a common
 *  goal and a fixed calendar window (typically 1–2 weeks).
 *
 *  task_goal stores the total story points the team committed to
 *  for this sprint (sprint commitment). Comparing task_goal against
 *  the sum of completed story points gives the sprint's velocity
 *  completion ratio — see SprintTTService.getSprintMetrics().
 *
 *  Oracle DDL:
 *    CREATE TABLE sprint_tt (
 *        spr_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *        name_sprint     VARCHAR2(100),
 *        date_start_spr  DATE,
 *        date_end_spr    DATE,
 *        task_goal       NUMBER,
 *        state_sprint    VARCHAR2(30) CHECK (state_sprint IN ('done', 'active')),
 *        pj_id           NUMBER REFERENCES project_tt(pj_id) ON DELETE CASCADE
 *    );
 */
@Entity
@Table(name = "SPRINT_TT")
public class SprintTT {

    /*
     * Surrogate primary key — auto-generated by Oracle IDENTITY.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "SPR_ID")
    private long sprId;

    /*
     * Human-readable sprint label (e.g., "Sprint 1: Security").
     * Helps the team quickly identify the sprint's focus.
     */
    @Column(name = "NAME_SPRINT", length = 100)
    private String nameSprint;

    /*
     * The calendar date on which this sprint officially starts.
     */
    @Column(name = "DATE_START_SPR")
    private LocalDate dateStartSpr;

    /*
     * The calendar date on which this sprint ends.
     * Tasks still 'active' past this date become 'delayed' in SPRINT_TASK_TT.
     */
    @Column(name = "DATE_END_SPR")
    private LocalDate dateEndSpr;

    /*
     * Story point commitment for this sprint (the sprint goal capacity).
     * Integer is nullable — goal may be set after sprint creation.
     */
    @Column(name = "TASK_GOAL")
    private Integer taskGoal;

    /*
     * Lifecycle state of the sprint.
     * 'active' — sprint is currently running; tasks are being worked.
     * 'done'   — sprint closed; all tasks have a final state.
     * Only one sprint per project should be 'active' at a time.
     */
    @Column(name = "STATE_SPRINT", length = 30)
    private String stateSprint;

    /*
     * The project this sprint belongs to.
     * A project can have many sequential sprints over its lifetime.
     */
    @Column(name = "PJ_ID")
    private long pjId;

    // ─── Constructors ────────────────────────────────────────────────────

    /** Required no-args constructor for JPA. */
    public SprintTT() {}

    /** Full constructor for programmatic sprint creation. */
    public SprintTT(long sprId, String nameSprint, LocalDate dateStartSpr,
                    LocalDate dateEndSpr, Integer taskGoal,
                    String stateSprint, long pjId) {
        this.sprId       = sprId;
        this.nameSprint  = nameSprint;
        this.dateStartSpr = dateStartSpr;
        this.dateEndSpr  = dateEndSpr;
        this.taskGoal    = taskGoal;
        this.stateSprint = stateSprint;
        this.pjId        = pjId;
    }

    // ─── Getters & Setters ───────────────────────────────────────────────

    public long getSprId()                       { return sprId; }
    public void setSprId(long sprId)             { this.sprId = sprId; }

    public String getNameSprint()                { return nameSprint; }
    public void setNameSprint(String nameSprint) { this.nameSprint = nameSprint; }

    public LocalDate getDateStartSpr()           { return dateStartSpr; }
    public void setDateStartSpr(LocalDate d)     { this.dateStartSpr = d; }

    public LocalDate getDateEndSpr()             { return dateEndSpr; }
    public void setDateEndSpr(LocalDate d)       { this.dateEndSpr = d; }

    public Integer getTaskGoal()                 { return taskGoal; }
    public void setTaskGoal(Integer taskGoal)    { this.taskGoal = taskGoal; }

    public String getStateSprint()               { return stateSprint; }
    public void setStateSprint(String s)         { this.stateSprint = s; }

    public long getPjId()                        { return pjId; }
    public void setPjId(long pjId)               { this.pjId = pjId; }
}
