package com.springboot.MyTodoList.model;

import jakarta.persistence.*;
import java.time.LocalDate;

/*
 * ============================================================
 *  Entity: SubTaskTT
 *  Table:  SUBTASK_TT
 * ============================================================
 *
 *  Represents a smaller subtask broken down from a main task.
 *  Allows for more granular tracking of progress.
 *
 *  Key design decisions:
 *    - task_id is stored as a plain long FK (not @ManyToOne
 *      relationships) to keep the entity lightweight and consistent.
 *    - priority_sub and state_sub are Strings with DB-level CHECK constraints
 *      rather than Java enums — keeps Oracle as the single source of truth.
 *    - Story points are Integer (nullable) because estimation may
 *      happen after subtask creation.
 *
 *  Oracle DDL:
 *    CREATE TABLE subtask_tt (
 *        sub_id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *        name_sub            VARCHAR2(300),
 *        story_points_sub    NUMBER,
 *        date_start_sub      DATE,
 *        date_end_set_sub    DATE,
 *        date_end_real_sub   DATE,
 *        priority_sub        VARCHAR2(30) CHECK (priority_sub IN ('high', 'medium', 'low')),
 *        state_sub           VARCHAR2(30) CHECK (state_sub IN ('done', 'delayed', 'active')),
 *        info_sub            VARCHAR2(2000),
 *        task_id             NUMBER NOT NULL REFERENCES task_tt(task_id) ON DELETE CASCADE
 *    );
 */
@Entity
@Table(name = "SUBTASK_TT")
public class SubTaskTT {

    /*
     * Surrogate primary key — auto-generated by Oracle IDENTITY.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "SUB_ID")
    private long subId;

    /*
     * Short name / title of the subtask.
     */
    @Column(name = "NAME_SUB", length = 300)
    private String nameSub;

    /*
     * Agile estimation in Story Points.
     * Integer (not int) so it can be NULL when the subtask hasn't been estimated yet.
     */
    @Column(name = "STORY_POINTS_SUB")
    private Integer storyPointsSub;

    /*
     * The date work on this specific subtask actually started.
     */
    @Column(name = "DATE_START_SUB")
    private LocalDate dateStartSub;

    /*
     * The planned completion date for this subtask.
     */
    @Column(name = "DATE_END_SET_SUB")
    private LocalDate dateEndSetSub;

    /*
     * The date the subtask was actually completed.
     * Remains NULL while the subtask is still in progress.
     */
    @Column(name = "DATE_END_REAL_SUB")
    private LocalDate dateEndRealSub;

    /*
     * Priority tier for the subtask.
     * Accepted values (enforced by Oracle CHECK constraint):
     *   'high', 'medium', 'low'
     */
    @Column(name = "PRIORITY_SUB", length = 30)
    private String prioritySub;

    /*
     * Current state of the subtask.
     * Accepted values (enforced by Oracle CHECK constraint):
     *   'done', 'delayed', 'active'
     */
    @Column(name = "STATE_SUB", length = 30)
    private String stateSub;

    /*
     * Extra info or description for the subtask.
     */
    @Column(name = "INFO_SUB", length = 2000)
    private String infoSub;

    /*
     * The main task this subtask belongs to.
     * Every subtask must belong to exactly one task.
     */
    @Column(name = "TASK_ID", nullable = false)
    private long taskId;

    // ─── Constructors ────────────────────────────────────────────────────

    /** Required no-args constructor for JPA. */
    public SubTaskTT() {
    }

    /** Full constructor for programmatic subtask creation. */
    public SubTaskTT(String nameSub, Integer storyPointsSub, LocalDate dateStartSub, 
                     LocalDate dateEndSetSub, LocalDate dateEndRealSub, 
                     String prioritySub, String stateSub, String infoSub, long taskId) {
        this.nameSub = nameSub;
        this.storyPointsSub = storyPointsSub;
        this.dateStartSub = dateStartSub;
        this.dateEndSetSub = dateEndSetSub;
        this.dateEndRealSub = dateEndRealSub;
        this.prioritySub = prioritySub;
        this.stateSub = stateSub;
        this.infoSub = infoSub;
        this.taskId = taskId;
    }

    // ─── Getters & Setters ───────────────────────────────────────────────

    public long getSubId()                              { return subId; }
    public void setSubId(long subId)                    { this.subId = subId; }

    public String getNameSub()                          { return nameSub; }
    public void setNameSub(String nameSub)              { this.nameSub = nameSub; }

    public Integer getStoryPointsSub()                  { return storyPointsSub; }
    public void setStoryPointsSub(Integer storyPointsSub) { this.storyPointsSub = storyPointsSub; }

    public LocalDate getDateStartSub()                  { return dateStartSub; }
    public void setDateStartSub(LocalDate d)            { this.dateStartSub = d; }

    public LocalDate getDateEndSetSub()                 { return dateEndSetSub; }
    public void setDateEndSetSub(LocalDate d)           { this.dateEndSetSub = d; }

    public LocalDate getDateEndRealSub()                { return dateEndRealSub; }
    public void setDateEndRealSub(LocalDate d)          { this.dateEndRealSub = d; }

    public String getPrioritySub()                      { return prioritySub; }
    public void setPrioritySub(String prioritySub)      { this.prioritySub = prioritySub; }

    public String getStateSub()                         { return stateSub; }
    public void setStateSub(String stateSub)            { this.stateSub = stateSub; }

    public String getInfoSub()                          { return infoSub; }
    public void setInfoSub(String infoSub)              { this.infoSub = infoSub; }

    public long getTaskId()                             { return taskId; }
    public void setTaskId(long taskId)                  { this.taskId = taskId; }
}
