package com.springboot.MyTodoList.model;

import jakarta.persistence.*;
import java.time.LocalDate;

/*
 * ============================================================
 *  Entity: TaskTT
 *  Table:  TASK_TT
 * ============================================================
 *
 *  Represents a single work item (user story, bug, chore, etc.)
 *  within a project. Tasks are the atomic unit of work tracked
 *  by sprints and story-point velocity.
 *
 *  Key design decisions:
 *    - user_id and pj_id are stored as plain long FKs (not @ManyToOne
 *      relationships) to keep the entity lightweight and consistent
 *      with the existing codebase style.
 *    - priority is a String with a DB-level CHECK constraint rather
 *      than a Java enum — keeps Oracle as the single source of truth
 *      for allowed values.
 *    - Story points are Integer (nullable) because estimation may
 *      happen after task creation.
 *
 *  Oracle DDL:
 *    CREATE TABLE task_tt (
 *        task_id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *        name_task           VARCHAR2(300),
 *        story_points        NUMBER,
 *        date_start_task     DATE,
 *        date_end_set_task   DATE,
 *        date_end_real_task  DATE,
 *        priority            VARCHAR2(30) CHECK (priority IN ('high', 'medium', 'low')),
 *        user_id             NUMBER NOT NULL REFERENCES user_tt(user_id)   ON DELETE CASCADE,
 *        pj_id               NUMBER NOT NULL REFERENCES project_tt(pj_id) ON DELETE CASCADE
 *    );
 */
@Entity
@Table(name = "TASK_TT")
public class TaskTT {

    /*
     * Surrogate primary key — auto-generated by Oracle IDENTITY.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "TASK_ID")
    private long taskId;

    /*
     * Short name / title of the task (e.g., "Implement OAuth Login").
     */
    @Column(name = "NAME_TASK", length = 300)
    private String nameTask;

    /*
     * Agile estimation in Story Points.
     * Aggregated by SprintTTService.getSprintMetrics() to compute velocity.
     * Integer (not int) so it can be NULL when the task hasn't been estimated yet.
     */
    @Column(name = "STORY_POINTS")
    private Integer storyPoints;

    /*
     * The date work on this specific task actually started.
     */
    @Column(name = "DATE_START_TASK")
    private LocalDate dateStartTask;

    /*
     * The planned completion date for this task (set during sprint planning).
     */
    @Column(name = "DATE_END_SET_TASK")
    private LocalDate dateEndSetTask;

    /*
     * The date the task was actually completed.
     * Remains NULL while the task is still in progress.
     * Compared with date_end_set_task to detect delayed tasks.
     */
    @Column(name = "DATE_END_REAL_TASK")
    private LocalDate dateEndRealTask;

    /*
     * Priority tier for the task.
     * Accepted values (enforced by Oracle CHECK constraint):
     *   'high'   — must be done this sprint
     *   'medium' — should be done this sprint
     *   'low'    — nice to have this sprint
     */
    @Column(name = "PRIORITY", length = 30)
    private String priority;

    /*
     * The user currently assigned to this task.
     * Before reassigning, TaskTTService.safeAssignTask() verifies
     * that the new user is a member of the task's project (via PROJECT_USER_TT).
     */
    @Column(name = "USER_ID", nullable = false)
    private long userId;

    /*
     * The project this task belongs to.
     * Every task must belong to exactly one project.
     */
    @Column(name = "PJ_ID", nullable = false)
    private long pjId;

    // ─── Constructors ────────────────────────────────────────────────────

    /** Required no-args constructor for JPA. */
    public TaskTT() {}

    /** Full constructor for programmatic task creation. */
    public TaskTT(long taskId, String nameTask, Integer storyPoints,
                  LocalDate dateStartTask, LocalDate dateEndSetTask,
                  LocalDate dateEndRealTask, String priority,
                  long userId, long pjId) {
        this.taskId          = taskId;
        this.nameTask        = nameTask;
        this.storyPoints     = storyPoints;
        this.dateStartTask   = dateStartTask;
        this.dateEndSetTask  = dateEndSetTask;
        this.dateEndRealTask = dateEndRealTask;
        this.priority        = priority;
        this.userId          = userId;
        this.pjId            = pjId;
    }

    // ─── Getters & Setters ───────────────────────────────────────────────

    public long getTaskId()                         { return taskId; }
    public void setTaskId(long taskId)              { this.taskId = taskId; }

    public String getNameTask()                     { return nameTask; }
    public void setNameTask(String nameTask)        { this.nameTask = nameTask; }

    public Integer getStoryPoints()                 { return storyPoints; }
    public void setStoryPoints(Integer storyPoints) { this.storyPoints = storyPoints; }

    public LocalDate getDateStartTask()             { return dateStartTask; }
    public void setDateStartTask(LocalDate d)       { this.dateStartTask = d; }

    public LocalDate getDateEndSetTask()            { return dateEndSetTask; }
    public void setDateEndSetTask(LocalDate d)      { this.dateEndSetTask = d; }

    public LocalDate getDateEndRealTask()           { return dateEndRealTask; }
    public void setDateEndRealTask(LocalDate d)     { this.dateEndRealTask = d; }

    public String getPriority()                     { return priority; }
    public void setPriority(String priority)        { this.priority = priority; }

    public long getUserId()                         { return userId; }
    public void setUserId(long userId)              { this.userId = userId; }

    public long getPjId()                           { return pjId; }
    public void setPjId(long pjId)                  { this.pjId = pjId; }
}
