package com.springboot.MyTodoList.model;

import jakarta.persistence.*;

/*
 * ============================================================
 *  Entity: UserTT
 *  Table:  USER_TT
 * ============================================================
 *
 *  Represents a user registered in the TaskTuner system.
 *  Users are identified by their Telegram handle, which the bot
 *  uses to dispatch notifications and commands.
 *
 *  Role is a discriminator — 'manager' users can create/delete
 *  projects and assign tasks; 'developer' users work on tasks.
 *
 *  Oracle DDL:
 *    CREATE TABLE user_tt (
 *        user_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *        name_user   VARCHAR2(100) NOT NULL,
 *        password    VARCHAR2(100),
 *        id_telegram VARCHAR2(200) NOT NULL,
 *        mail        VARCHAR2(200),
 *        role        VARCHAR2(20) NOT NULL
 *            CHECK (role IN ('manager', 'developer'))
 *    );
 */
@Entity
@Table(name = "USER_TT")
public class UserTT {

    /*
     * Primary key — Oracle generates this automatically via the
     * IDENTITY column (equivalent to AUTO_INCREMENT in MySQL).
     * GenerationType.IDENTITY tells Hibernate to rely on the DB sequence.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "USER_ID")
    private long userId;

    /*
     * Full display name of the user (e.g., "Alice Manager").
     * NOT NULL in DB — Hibernate enforces this at the Java level via nullable = false.
     */
    @Column(name = "NAME_USER", nullable = false, length = 100)
    private String nameUser;

    /*
     * Stored password (should be hashed with BCrypt before saving).
     * Nullable — some OAuth/Telegram-only users may not have a password.
     */
    @Column(name = "PASSWORD", length = 100)
    private String password;

    /*
     * Telegram username or chat ID used by the bot to send messages
     * directly to this user (e.g., "@alice_tg" or a numeric chat ID).
     * NOT NULL — every user must be reachable via Telegram.
     */
    @Column(name = "ID_TELEGRAM", nullable = false, length = 200)
    private String idTelegram;

    /*
     * Optional email address for email notifications or account recovery.
     */
    @Column(name = "MAIL", length = 200)
    private String mail;

    /*
     * Role of the user within the platform.
     * Accepted values (enforced by Oracle CHECK constraint):
     *   'manager'   — can manage projects, assign tasks, view all metrics
     *   'developer' — can update task states, log work
     */
    @Column(name = "ROLE", nullable = false, length = 20)
    private String role;

    // ─── Constructors ────────────────────────────────────────────────────

    /**
     * No-args constructor required by JPA.
     * JPA creates entity instances via reflection, so this must exist.
     */
    public UserTT() {}

    /**
     * Full constructor — useful for building entities programmatically
     * in tests or service logic without relying on setters.
     */
    public UserTT(long userId, String nameUser, String password,
                  String idTelegram, String mail, String role) {
        this.userId     = userId;
        this.nameUser   = nameUser;
        this.password   = password;
        this.idTelegram = idTelegram;
        this.mail       = mail;
        this.role       = role;
    }

    // ─── Getters & Setters ───────────────────────────────────────────────

    public long getUserId()                    { return userId; }
    public void setUserId(long userId)         { this.userId = userId; }

    public String getNameUser()                { return nameUser; }
    public void setNameUser(String nameUser)   { this.nameUser = nameUser; }

    public String getPassword()                { return password; }
    public void setPassword(String password)   { this.password = password; }

    public String getIdTelegram()                    { return idTelegram; }
    public void setIdTelegram(String idTelegram)     { this.idTelegram = idTelegram; }

    public String getMail()                    { return mail; }
    public void setMail(String mail)           { this.mail = mail; }

    public String getRole()                    { return role; }
    public void setRole(String role)           { this.role = role; }
}
