package com.springboot.MyTodoList.util;

public enum BotConversationState {
    NONE,
    // Creación de tareas
    WAITING_NEW_ITEM_NAME,
    WAITING_NEW_ITEM_STORY_POINTS,
    WAITING_NEW_ITEM_PRIORITY,
    WAITING_NEW_ITEM_SPRINT,
    // Flujo de edición de tarea
    WAITING_EDIT_TASK_FIELD,
    WAITING_EDIT_TASK_NEW_NAME,
    WAITING_EDIT_TASK_NEW_SP,
    WAITING_EDIT_TASK_NEW_PRIORITY,
    WAITING_EDIT_TASK_NEW_SPRINT,
    // Flujo de creación de cuenta
    WAITING_REGISTER_NAME,
    WAITING_REGISTER_EMAIL,
    WAITING_REGISTER_PASSWORD,
    WAITING_REGISTER_PASSWORD_CONFIRM,

}
